In [1]:
# 범주형 데이터 실수화

import pandas as pd # pandas package import

In [4]:
from sklearn.preprocessing import LabelEncoder # 범주형 데이터
from sklearn.preprocessing import OneHotEncoder # 더미변수 생성, 가변환 함수 임포트

In [90]:
# 데이터 set 생성
x_train = pd.DataFrame(["남성", '여성', '남성', '여성', '남성', '여성'], columns = ['성별'])

In [91]:
# 데이터 확인
x_train.head(5)

성별
0  남성
1  여성
2  남성
3  여성
4  남성

In [92]:
x_train.info() # 데이터 프레임의 정보를 확인한다. 
# object 타입 '성별' 변수.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   성별      6 non-null      object
dtypes: object(1)
memory usage: 176.0+ bytes


In [93]:
x_train['성별'].value_counts() # 범주형 데이터의 갯수 확인

남성    3
여성    3
Name: 성별, dtype: int64

### 레이블 인코딩 : 문자를 0 부터 시작하는 정수형 숫자로 변환'

In [95]:
# 레이블 인코더 생성
encoding = LabelEncoder()

In [96]:
# x_train 데이터를 이용하여 피팅하고 레이블 숫자로 변환
encoding.fit(x_train['성별'])
x_train["성별_인코딩"] = encoding.transform(x_train['성별'])

In [97]:
x_train # 인코딩 결과값 확인

성별  성별_인코딩
0  남성       0
1  여성       1
2  남성       0
3  여성       1
4  남성       0
5  여성       1

In [98]:
print(list(encoding.classes_)) #클래스 확인
print(list(encoding.inverse_transform([1,0]))) # 인코딩 값으로 문자값 확인

['남성', '여성']
['여성', '남성']


In [99]:
print(list(encoding.inverse_transform([1,0]))) # 인코딩 값으로 문자값 확인

['여성', '남성']


In [100]:
''' 원핫 인코딩 '''

' 원핫 인코딩 '

In [101]:
x_train.head(2) # 데이터 확인

성별  성별_인코딩
0  남성       0
1  여성       1

In [102]:
# 원핫 인코더 생성
# sparse 를 True 로 할 경우 " (행, 열) 1" 의 좌표리스트의 형식, False 의 경우 넘파이 배열로 변환
one_encoding = OneHotEncoder (sparse = False) # 넘파이 배열로 변환

In [103]:
# X_trian 데이터를 이용하여 피팅
one_encoding.fit(x_train[['성별']])

OneHotEncoder(sparse=False)

In [104]:
# 가변환값 변환
one_encoding.transform(x_train[['성별']])

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [105]:
one_encoding.fit_transform(x_train[['성별']]) # 피팅

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [106]:
# 가변환된 피쳐 확인
print(one_encoding.get_feature_names())

['x0_남성' 'x0_여성']


C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [109]:
# 가변환된 값을 x_train_one 데이터 프레임으로 저장한다
x_train_one = pd.DataFrame(one_encoding.transform(x_train[['성별']]),columns = ['성별0','성별1'])
x_train_one

성별0  성별1
0  1.0  0.0
1  0.0  1.0
2  1.0  0.0
3  0.0  1.0
4  1.0  0.0
5  0.0  1.0

In [110]:
# x_train 데이터와 x_train_one 의 가변환된 속성을 합친다.
x_train = pd.concat([x_train,x_train_one], axis = 1)

In [112]:
x_train.head()

성별  성별_인코딩  성별0  성별1
0  남성       0  1.0  0.0
1  여성       1  0.0  1.0
2  남성       0  1.0  0.0
3  여성       1  0.0  1.0
4  남성       0  1.0  0.0

In [ ]:
''' 데이터 정제 - 텍스트 데이터 실수화 '''

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
corpus = [
            '청년 인재 개발 양성 과정',
            ' 인공지능 청년 양성' ,
            ' 미래 인공지능  데이터 대한민국',
            ' 데이터 원유  기술사 청년 개발'
    
            ]

In [49]:
corpus

['청년 인재 개발 양성 과정', ' 인공지능 청년 양성', ' 미래 인공지능  데이터 대한민국', ' 데이터 원유  기술사 청년 개발']

In [50]:
type(corpus)

list

In [51]:
# 카운트 벡터라이저 생성
count_vect = CountVectorizer ()

In [52]:
# 단어 카운트, corpus 피팅
count_vect.fit(corpus)

CountVectorizer()

In [53]:
# 단어확인
count_vect.vocabulary_

{'청년': 10,
 '인재': 9,
 '개발': 0,
 '양성': 6,
 '과정': 1,
 '인공지능': 8,
 '미래': 5,
 '데이터': 4,
 '대한민국': 3,
 '원유': 7,
 '기술사': 2}

In [55]:
# 단어 벡터화한 값을 array 로 변환하여 확인
count_vect.transform(corpus).toarray()

array([[1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1]], dtype=int64)

In [68]:
# 단어 벡터화
features = count_vect.transform(corpus)

In [69]:
features

<4x11 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [70]:
# 속성 이름만 반환
vocab = count_vect.get_feature_names()

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [71]:
vocab # 속성 이름만 반환되었다.

['개발', '과정', '기술사', '대한민국', '데이터', '미래', '양성', '원유', '인공지능', '인재', '청년']

In [72]:
# 문서단어행렬을 데이터 프레임으로 변환
DTM = pd.DataFrame(features.toarray(), columns = vocab_idf).head()
DTM

개발  과정  기술사  대한민국  데이터  미래  양성  원유  인공지능  인재  청년
0   1   1    0     0    0   0   1   0     0   1   1
1   0   0    0     0    0   0   1   0     1   0   1
2   0   0    0     1    1   1   0   0     1   0   0
3   1   0    1     0    1   0   0   1     0   0   1

In [73]:
# 문서 단어 행렬에 일치하는 단어 확인
count_vect.transform(['기술사 대한민국 인재 만세']).toarray()

array([[0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [ ]:
''' TfidVectorizer 함수 : TF-IDF 방ㅅ식으로 단어의 가중치를 조정한 bow 로 인코딩하는 함수'''

In [75]:
# 필요 라이브러리 import
from sklearn.feature_extraction.text import TfidfVectorizer

In [76]:
corpus

['청년 인재 개발 양성 과정', ' 인공지능 청년 양성', ' 미래 인공지능  데이터 대한민국', ' 데이터 원유  기술사 청년 개발']

In [77]:
# TF-IDF 벡터라이저 생성
tfid = TfidfVectorizer()

In [78]:
# 단어 카운트
tfid.fit(corpus)

TfidfVectorizer()

In [81]:
# 단어사전 확인
tfid.vocabulary_

{'청년': 10,
 '인재': 9,
 '개발': 0,
 '양성': 6,
 '과정': 1,
 '인공지능': 8,
 '미래': 5,
 '데이터': 4,
 '대한민국': 3,
 '원유': 7,
 '기술사': 2}

In [82]:
# 단어 벡터화한 값을 array로 변환하여 확인
tfid.transform(corpus).toarray() # 중요성을 수치화

array([[0.41263976, 0.52338122, 0.        , 0.        , 0.        ,
        0.        , 0.41263976, 0.        , 0.        , 0.52338122,
        0.33406745],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.61366674, 0.        , 0.61366674, 0.        ,
        0.49681612],
       [0.        , 0.        , 0.        , 0.55528266, 0.43779123,
        0.55528266, 0.        , 0.        , 0.43779123, 0.        ,
        0.        ],
       [0.41263976, 0.        , 0.52338122, 0.        , 0.41263976,
        0.        , 0.        , 0.52338122, 0.        , 0.        ,
        0.33406745]])

In [83]:
# 단어 벡터화
features_idf = tfid.transform(corpus)

In [84]:
features_idf

<4x11 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [85]:
# 속성 이름만 반환
vocab_idf = count_vect.get_feature_names()

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [86]:
vocab_idf

['개발', '과정', '기술사', '대한민국', '데이터', '미래', '양성', '원유', '인공지능', '인재', '청년']

In [87]:
# 문서단어행렬(DTM) 을 데이터 프레임으로 변환
DTM_idf = pd.DataFrame(features_idf.toarray(), columns = vocab_idf).head()
DTM_idf

개발        과정       기술사      대한민국       데이터        미래        양성  \
0  0.41264  0.523381  0.000000  0.000000  0.000000  0.000000  0.412640   
1  0.00000  0.000000  0.000000  0.000000  0.000000  0.000000  0.613667   
2  0.00000  0.000000  0.000000  0.555283  0.437791  0.555283  0.000000   
3  0.41264  0.000000  0.523381  0.000000  0.412640  0.000000  0.000000   

         원유      인공지능        인재        청년  
0  0.000000  0.000000  0.523381  0.334067  
1  0.000000  0.613667  0.000000  0.496816  
2  0.000000  0.437791  0.000000  0.000000  
3  0.523381  0.000000  0.000000  0.334067