In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.rand(2,3)

array([[0.37855539, 0.07203085, 0.17992507],
       [0.24180539, 0.17619388, 0.36015702]])

In [11]:
# 배열생성
arr2 = np.arange(16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
arr.shape # 16열로만 이루어져있다.

(16,)

In [17]:
arr.dtype # 정수형이라는 것

dtype('int32')

In [18]:
arr. astype(float) # 실수형으로 바꾼 것이다.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [20]:
# 기본  인덱스
arr[5]

5

In [22]:
arr[-1]

15

In [23]:
arr[5:8]

array([5, 6, 7])

In [25]:
arr2 = np.arange(16).reshape(4,4) # 메서드 체인
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
arr2[1] #2번째 행을 보여준다.(0,1,2,3..이므로)

array([4, 5, 6, 7])

In [28]:
arr2[1,1] # 2번째 행 2번째 열에 있는 element 를 보여준다.

5

In [29]:
# 불리언 인덱스를 사용한 선택
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [31]:
score_arr >= 90 # 불리언값으로 보여준다. 90보다 큰 것이 True

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [33]:
score_arr[score_arr >= 90] = 999 # 90보다 큰 요소를 999로 만들어준다.

In [34]:
# 주요연산
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [35]:
arr + 2

array([3, 4, 5, 6])

In [36]:
arr * 2

array([2, 4, 6, 8])

In [37]:
list = [1,2,3,4]
list

[1, 2, 3, 4]

In [38]:
list * 2 # 반복할 수 있다.

[1, 2, 3, 4, 1, 2, 3, 4]

In [39]:
arr1 = np.arange(5,9)
arr1

array([5, 6, 7, 8])

In [40]:
arr + arr1

array([ 6,  8, 10, 12])

In [41]:
list1 = [5,6,7,8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

In [44]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])